// <auto-generated />
namespace SCADA_Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Tag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tag));
        
        string IMigrationMetadata.Id
        {
            get { return "201901181550366_Tag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
